<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0-windows</TargetFrameworks>
    <RootNamespace>FontStashSharp.Base.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FontStashSharp.TextShapers.HarfBuzz\FontStashSharp.TextShapers.HarfBuzz.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <ProjectReference Include="..\..\src\FontStashSharp.Rasterizers.SharpAstro\FontStashSharp.Rasterizers.SharpAstro.csproj" />
  </ItemGroup>

</Project>
