<Project>
  <PropertyGroup>
    <Authors>FontStashSharpTeam</Authors>
    <Product>FontStashSharp</Product>
    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/FontStashSharp/FontStashSharp.Base</PackageProjectUrl>
    <RootNamespace>FontStashSharp</RootNamespace>
    <Version>1.2.9</Version>
    <TargetFrameworks>netstandard2.0;net471;net8.0</TargetFrameworks>
  </PropertyGroup>
</Project>